# Generated by Django 5.2.10 on 2026-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
