# Generated by Django 5.2.10 on 2026-05-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_intro_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
