# Generated by Django 5.2.10 on 2026-05-16 11:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('image', 0), ('cta', 1), ('anchor', 2), ('headline', 3), ('sub_headline', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'call_to_action'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor'}), 3: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
    ]
