# Generated by Django 5.2.10 on 2026-05-16 19:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('Hero', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'orm_classname': 'CTA'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('cta', 1), ('anchor', 2), ('headline', 3), ('sub_headline', 3)]], {})}, null=True),
        ),
    ]
