# Generated by Django 5.2.10 on 2026-05-19 11:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='problem',
            field=wagtail.fields.StreamField([('Problem', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Tag'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Beschreibung'}), 3: ('wagtail.blocks.StructBlock', [[('tag', 0), ('heading', 1), ('paragrapgh', 2)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='problem_card',
            field=wagtail.fields.StreamField([('ProblemCard', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Icon'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Beschreibung'}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('heading', 1), ('paragrapgh', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('Hero', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Bild'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'CTA'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Anchor Link', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Headline'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Sub Headline', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('cta', 1), ('anchor', 2), ('headline', 3), ('sub_headline', 4)]], {})}, null=True),
        ),
    ]
