# Generated by Django 5.2.10 on 2026-05-19 19:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_problem_homepage_problem_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='problem',
            field=wagtail.fields.StreamField([('Problem', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Tag'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Beschreibung'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Anchor Link', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('tag', 0), ('heading', 1), ('paragraph', 2), ('anchor', 3)]], {})}, null=True),
        ),
    ]
