# Generated by Django 5.2.10 on 2026-05-19 19:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='problem_card',
            field=wagtail.fields.StreamField([('ProblemCard', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Icon'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Beschreibung'}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('heading', 1), ('paragraph', 2)]], {})}, null=True),
        ),
    ]
