# Generated by Django 5.2.10 on 2026-07-08 19:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_problem_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('Hero', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Bild'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'CTA'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Anchor Link', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Anchor Name', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Headline'}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Sub Headline', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('cta', 1), ('anchor', 2), ('anchor_name', 3), ('headline', 4), ('sub_headline', 5)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='problem',
            field=wagtail.fields.StreamField([('Problem', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Tag'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Beschreibung'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Anchor Link', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Anchor Name', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('tag', 0), ('heading', 1), ('paragraph', 2), ('anchor', 3), ('anchor_name', 4)]], {})}, null=True),
        ),
    ]
