# Generated by Django 5.2.10 on 2026-07-13 11:18

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_hero_alter_homepage_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='problem_card',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('problem', 13), ('problem_card', 11), ('form_section', 18)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Bild'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'CTA'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Anchor Link', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Anchor Name', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Headline'}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Sub Headline', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('cta', 1), ('anchor', 2), ('anchor_name', 3), ('headline', 4), ('sub_headline', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Tag'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Beschreibung'}), 10: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Icon'}), 11: ('wagtail.blocks.StructBlock', [[('icon', 10), ('heading', 8), ('paragraph', 9)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Problem Cards', 'max_num': 3, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('tag', 7), ('heading', 8), ('paragraph', 9), ('anchor', 2), ('anchor_name', 3), ('cards', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Überschrift', 'required': False}), 15: ('wagtail.blocks.RichTextBlock', (), {'label': 'Einleitung', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Anchor Name / HTML ID', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Absenden', 'label': 'Button Text', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('heading', 14), ('intro', 15), ('anchor', 2), ('anchor_name', 16), ('submit_label', 17)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='from_address',
            field=models.EmailField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address'),
        ),
        migrations.CreateModel(
            name='HomePageFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
