# Generated by Django 5.2.10 on 2026-07-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_formpage_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
